server:
  port: 8080
  jsp-servlet:
      init-parameters:
         development: true
  
spring:
    mvc:
       view:
          prefix: /WEB-INF/jsp/
          suffix: .jsp
#数据库连接
    datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/tj?characterEncoding=UTF-8&serverTimezone=UTC
       username: root
       password: ecwalk
       type: com.zaxxer.hikari.HikariDataSource
#hikari连接池
       hikari: 
           minimum-idle: 5
           maximum-pool-size: 15
           auto-commit: true
           idle-timeout: 30000
           pool-name: DatebookHikariCP
           max-lifetime: 1800000
           connection-timeout: 30000
           connection-test-query: SELECT 1
#jpa
    jpa: 
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
           
          
 